/**
 * The catalogue, read once from the generated JSON data.
 *
 * `scripts/import-products.ts` is the only writer; everything here is pure
 * lookups and small ordering helpers, so it runs in Server Components with no
 * client JavaScript and no runtime fetch to any external system.
 */

import categoriesFile from '@/data/categories.json'
import productsFile from '@/data/products.json'
import { categoryOrder } from '@/lib/content/navigation'
import { hasPrice } from '@/lib/catalogue/pricing'
import type { Category, CategoryTree, Catalogue, Product } from '@/types/catalogue'

export { effectivePricePKR, hasPrice, isOnSale } from '@/lib/catalogue/pricing'
export { isProductSort, productSortOptions, sortProducts } from '@/lib/catalogue/sorts'
export type { ProductSort } from '@/lib/catalogue/sorts'

/**
 * The JSON is generated by the import script from the audited source data; the
 * cast keeps the app typed as the documented catalogue shape instead of the
 * inferred literal type of the file.
 */
const catalogue = productsFile as unknown as Catalogue
const tree = categoriesFile as unknown as CategoryTree

export const allProducts: Product[] = catalogue.products
export const allCategories: Category[] = tree.categories

/** Data freshness for the build reports. */
export const catalogueGeneratedAt: string = catalogue.generatedAt

const productsBySlug = new Map(allProducts.map((product) => [product.slug, product]))
const categoriesByPath = new Map(allCategories.map((category) => [category.path, category]))

export function getProduct(slug: string): Product | undefined {
  return productsBySlug.get(slug)
}

export function getAllProductSlugs(): string[] {
  return allProducts.map((product) => product.slug)
}

export function getCategory(path: string): Category | undefined {
  return categoriesByPath.get(path.replace(/^\/+|\/+$/g, ''))
}

/** `/product-category/bath/towels/` → the `bath/towels` category. */
export function getCategoryFromSegments(segments: string[] | undefined): Category | undefined {
  if (!segments || segments.length === 0) return undefined
  return getCategory(segments.join('/'))
}

export function getCategoryTree(): CategoryTree {
  return tree
}

export function productHref(product: Pick<Product, 'slug'>): string {
  return `/product/${product.slug}/`
}

export function categoryHref(path: string): string {
  return `/product-category/${path.replace(/^\/+|\/+$/g, '')}/`
}

/** Products filed directly under a category, or anywhere beneath it. */
export function productsInCategory(path: string, options?: { includeDescendants?: boolean }): Product[] {
  const includeDescendants = options?.includeDescendants ?? true
  const normalised = path.replace(/^\/+|\/+$/g, '')
  return allProducts.filter((product) =>
    product.categories.some((ref) => ref.path === normalised || (includeDescendants && ref.path.startsWith(`${normalised}/`))),
  )
}

export function featuredProducts(limit = 8): Product[] {
  const featured = allProducts.filter((product) => product.featured)
  const rest = allProducts.filter((product) => !product.featured && product.images.length > 0)
  return [...featured, ...rest].slice(0, limit)
}

export function productsWithPhotography(): Product[] {
  return allProducts.filter((product) => product.images.length > 0)
}

export type ProductFilters = {
  query?: string
  /** Leaf category path, e.g. `bath/towels/bathrobes`. */
  categoryPath?: string
  priceState?: 'all' | 'priced' | 'ask'
  color?: string
  /** Normalised material family, as returned by `materialFamily`. */
  material?: string
}

/**
 * The source material strings are noisy — `Cotton`, `100% Cotton` and
 * `Zero Twist Bathrobe - Cotton` are all the same fibre, and one row even carries
 * the product name. Everything is folded into four families so the sidebar reads
 * as a filter rather than a list of product titles.
 */
export function materialFamily(value: string | undefined): string | undefined {
  if (!value) return undefined
  const v = value.toLowerCase()
  if (v.includes('microfiber')) return 'Microfiber'
  if (v.includes('satin')) return 'Cotton Satin'
  if (v.includes('waffle')) return 'Waffle'
  if (v.includes('cotton')) return 'Cotton'
  return undefined
}

/** A rough swatch colour for a facet value, matched on keywords. */
export function colorSwatch(value: string): string {
  const v = value.toLowerCase()
  if (v.includes('white')) return '#f4f4f2'
  if (v.includes('cream')) return '#f0e6d6'
  if (v.includes('sand')) return '#ddcbb2'
  if (v.includes('grey') || v.includes('gray')) return '#9aa0a6'
  if (v.includes('black')) return '#1c1c1c'
  if (v.includes('mahroon') || v.includes('maroon')) return '#7b2b34'
  if (v.includes('red')) return '#c0392b'
  if (v.includes('fushia') || v.includes('fuchsia')) return '#d63384'
  if (v.includes('blossom') || v.includes('pink')) return '#e8a3b8'
  if (v.includes('purple')) return '#6f42c1'
  if (v.includes('yellow')) return '#e0b23c'
  if (v.includes('sky')) return '#8fc4e8'
  if (v.includes('blue')) return '#2a5d9e'
  if (v.includes('green')) return '#2f6b52'
  return '#c9c9c9'
}

function normalise(value: string): string {
  return value
    .toLowerCase()
    .replace(/[\u2013\u2014]/g, '-')
    .replace(/\s+/g, ' ')
    .trim()
}

export function matchesQuery(product: Product, query: string): boolean {
  const needle = normalise(query)
  if (!needle) return true
  const haystack = normalise(
    [
      product.name,
      product.sku ?? '',
      product.facets.color ?? '',
      product.facets.material ?? '',
      product.facets.gsm ?? '',
      product.tags.join(' '),
      product.categories.map((category) => category.name).join(' '),
      product.intro ?? '',
    ].join(' '),
  )
  return needle.split(' ').every((term) => haystack.includes(term))
}

export function filterProducts(list: Product[], filters: ProductFilters): Product[] {
  return list.filter((product) => {
    if (filters.query && !matchesQuery(product, filters.query)) return false
    if (filters.priceState === 'priced' && !hasPrice(product)) return false
    if (filters.priceState === 'ask' && hasPrice(product)) return false
    if (filters.color && normalise(product.facets.color ?? '') !== normalise(filters.color)) return false
    if (filters.material && materialFamily(product.facets.material) !== filters.material) return false
    if (filters.categoryPath) {
      const wanted = filters.categoryPath.replace(/^\/+|\/+$/g, '')
      const inCategory = product.categories.some(
        (ref) => ref.path === wanted || ref.path.startsWith(`${wanted}/`),
      )
      if (!inCategory) return false
    }
    return true
  })
}

export type FacetCount = { value: string; label: string; count: number }

/**
 * Counts for the shop sidebar, taken from the list the visitor is actually
 * looking at — so a count can never advertise products the grid will not show.
 * Categories are keyed by the product's own leaf category.
 */
export function facetCounts(list: Product[]): {
  categories: Array<FacetCount & { path: string }>
  materials: FacetCount[]
  colors: FacetCount[]
} {
  const categories = new Map<string, FacetCount & { path: string }>()
  const materials = new Map<string, FacetCount>()
  const colors = new Map<string, FacetCount>()

  for (const product of list) {
    const category = product.primaryCategory
    if (category) {
      const seen = categories.get(category.path)
      if (seen) seen.count += 1
      else categories.set(category.path, { path: category.path, value: category.path, label: category.name, count: 1 })
    }

    const material = materialFamily(product.facets.material)
    if (material) {
      const seen = materials.get(material)
      if (seen) seen.count += 1
      else materials.set(material, { value: material, label: material, count: 1 })
    }

    const color = product.facets.color?.trim()
    if (color) {
      const key = normalise(color)
      const seen = colors.get(key)
      if (seen) seen.count += 1
      else colors.set(key, { value: color, label: color, count: 1 })
    }
  }

  const byCount = (a: FacetCount, b: FacetCount) => b.count - a.count || a.label.localeCompare(b.label, 'en')

  return {
    categories: [...categories.values()].sort(byCount),
    materials: [...materials.values()].sort(byCount),
    colors: [...colors.values()].sort(byCount),
  }
}

/** Colours actually present in a list, for the filter chips. */
export function availableColors(list: Product[]): string[] {
  const colors = new Map<string, string>()
  for (const product of list) {
    const color = product.facets.color
    if (color && !colors.has(normalise(color))) colors.set(normalise(color), color)
  }
  return [...colors.values()].sort((a, b) => a.localeCompare(b, 'en'))
}

/** Same category first, then shared tags — never a fabricated cross-sell. */
export function relatedProducts(product: Product, limit = 4): Product[] {
  const paths = new Set(product.categories.map((category) => category.path))
  const tags = new Set(product.tags.map((tag) => tag.toLowerCase()))
  const scored = allProducts
    .filter((candidate) => candidate.slug !== product.slug)
    .map((candidate) => {
      const sharedCategory = candidate.categories.some((category) => paths.has(category.path)) ? 2 : 0
      const sharedTags = candidate.tags.filter((tag) => tags.has(tag.toLowerCase())).length
      const hasImage = candidate.images.length > 0 ? 0.5 : 0
      return { candidate, score: sharedCategory + sharedTags + hasImage }
    })
    .filter((entry) => entry.score > 0.5)
    .sort((a, b) => b.score - a.score || a.candidate.name.localeCompare(b.candidate.name, 'en'))

  return scored.slice(0, limit).map((entry) => entry.candidate)
}

/** Ancestors first, ending with the category itself. */
export function categoryBreadcrumb(path: string): Category[] {
  const segments = path.replace(/^\/+|\/+$/g, '').split('/')
  const trail: Category[] = []
  for (let index = 1; index <= segments.length; index += 1) {
    const category = getCategory(segments.slice(0, index).join('/'))
    if (category) trail.push(category)
  }
  return trail
}

/** Top-level categories with their children, in the order the live menus use. */
export function navigationCategories(): Array<{ category: Category; children: Category[] }> {
  const byPath = (a: Category, b: Category): number => {
    const left = categoryOrder.indexOf(a.path)
    const right = categoryOrder.indexOf(b.path)
    if (left === -1 || right === -1) return a.path.localeCompare(b.path)
    return left - right
  }

  return allCategories
    .filter((category) => category.depth === 0)
    .sort(byPath)
    .map((category) => ({
      category,
      children: category.children
        .map((path) => getCategory(path))
        .filter((child): child is Category => Boolean(child))
        .sort(byPath),
    }))
}
